### PR TITLE
REFACTOR: create python lib with CLI

### PR DESCRIPTION
**Pull request by balbasty**
I started the refactoring we talked about some time ago. See [draft document](https://docs.google.com/document/d/1OfaucLwkoCwKxi8GRzF2oKdqRniXL2A9fx9umOSq8ys/edit?tab=t.0)

I couldn't directly use [satra's template](https://github.com/sensein/python-package-template/tree/main) as our repo already exists, but used the same project.toml (almost -- I keep the package at the repo root, rather than under `src/`). I haven't added all the workflows and issue tempaltes yet. Let me know which ones you think we need.

@kabilar

### CODE REVIEW

**Comment by balbasty** [comment]
Thanks @calvinchai this looks great.

@jingjingwu1225 I have modified your multi-slice jp2000 converter. See `linc_convert/modalities/df/multi_slice.py`. The idea is to remove hardcoded references to the data organization. Instead you'll need to run it per subject, and to pass all of the input files (although a glob in the shell should work). Could you try it quickly on one of Suzanne's subjects?

**Comment by jingjingwu1225** [comment]
Hi @Yael, the reason I used 2**level in multiscales part is because it causes error if there is half voxel difference between 2 adjacent resolution levels when loading in webknossos.

**Comment by calvinchai** [comment]
@balbasty I just talked to Jingjing and I think we might need to fix the problem she mentioned and test it. But I think it might be better to first merge this and do another PR to keep things tracked and organized (we need to update test data file in this process). Also we can test if the GitHub action is working properly through this kind of push and PR. What do you think?

**Comment by balbasty** [comment]
I agree, let's merge this!

**Comment by balbasty** [comment]
Where are we at with this? Should we merge?

**Comment by calvinchai** [comment]
Sorry @balbasty , I was out sick yesterday and I will merge this now.

**Pull request merged**
